name: Ship js trigger
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: '@geospoc'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_PAT }}
      - run: npm run release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
